# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  dependencies:
    pre:
      - go get github.com/tcnksm/ghr

  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/drlogout/iredmail-cli
    steps:
      - checkout
      - run: sudo cp .circleci/doveadm /usr/local/bin/doveadm
      - run: sudo chmod a+x /usr/local/bin/doveadm
      - run: cp .iredmail-cli.yml $HOME/.iredmail-cli.yml
      - run: go get -v -t -d ./...
      - run: go test -v ./integration_test

  deployment:
    release:
      commands:
        — go get github.com/mitchellh/gox
        — go get github.com/tcnksm/ghr
        — gox -os="linux" -ldflags "-X main.Version $BUILD_VERSION -X main.BuildDate $BUILD_DATE" -output "output/ncd_{{.OS}}_{{.Arch}}"
      tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
      commands:
        - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` output/
